config/routes.rb
MatchPoint::Application.routes.draw do
  get "signup" => "users#new"
  post "users" => "users#create"
  get "login" => "sessions#new"
  get "purchase" => "purchases#new"
  post "purchases" => "purchases#create"
  get "logout" => "sessions#destroy"
  get "activate/:code" => "users#edit"
  get "all_users" => "users#index"

  resources :sessions
  resources :users
  resources :purchases
  root "sessions#new"

  

end

app/models/customer.rb
class Customer < User
	attr_accessor :password, :password_confirmation
	before_save :encrypt_password
	has_many :orders

end

app/models/instructor.rb
class Instructor < User
	attr_accessor :password, :password_confirmation
	before_save :encrypt_password
	has_many :orders

	field :hourly_rate, type: Integer
	field :years_of_experience, type: Integer
end

app/models/lesson.rb
class Lesson
  include Mongoid::Document
  embedded_in :order
  
  field :status, type: String
  field :dateused, type: Date
end

app/models/order.rb
class Order
  include Mongoid::Document
  belongs_to :customer
  embeds_many :lessons
  belongs_to :instructor

  field :price, type: Integer
  field :quantity, type: Integer
end

app/models/package.rb
class Package
	include Mongoid::Document

  field :quantity, type: Integer
  field :price, type: Integer
end

app/models/purchase.rb
class Purchase
  include Mongoid::Document
  attr_accessor :package, :price, :quantity, :name_first, :name_last, :phone, 					 :email, :number, :cvc, :exp_month, :exp_year, :instructor

  def save
    coach = Instructor.find(instructor)
    user = User.find_by(email: email)
    user.name_first = name_first
    user.name_last = name_last
    user.phone = phone
    lessons_array = []
    quantity.to_i.times do 
      lessons_array.push(Lesson.new(status: "Available", dateused: ''))
    end
        
    order = Order.new(price: price,
                      quantity: quantity,
                      customer_id: user.id,
                      instructor_id: coach.id,
                      lessons: lessons_array)

    user.save
    order.save
  end
end

app/models/stripe_model.rb
class StripeModel
  include Mongoid::Document

  def self.chargeCreditCard(token, email, quantity, amount)
		customer = Stripe::Customer.create(
      :email => email,
      :card  => token
    )

 		#charge user's credit card
    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => amount,
      :description => quantity + ' lesson package',
      :currency    => 'usd'
    )

    rescue Stripe::CardError => e
      puts "in rescue************"
      puts e.message
      # flash[:error] = e.message
      # redirect_to purchase_path
	end
end

app/models/user.rb
class User
  include Mongoid::Document
  attr_accessor :password, :password_confirmation
  before_save :encrypt_password

  # validates :password, confirmation: true
  # validates :password_confirmation, presence: true
  field :is_admin, type: Boolean, default: false
  field :name_first, type: String
  field :name_last, type: String
  field :phone, type: String
  field :email, type: String
  field :password_hash, type: String
 	field :salt, type: String
 	field :code, type: String
 	field :expires_at, type: Time
 	has_many :orders
  # one :credential

  def self.authenticate(email, password)
  	user = User.find_by(email: email)
  	
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.salt)
  		user
  	else
  		nil
  	end
	end
 	def encrypt_password
 		unless password.blank?
      self.salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, self.salt)
    end
 	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :is_instructor, :name_first

  private
	def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

  def name_first
    if current_user
      @name_first ||= current_user.name_first
    end
  end

  def is_instructor?(user)
    user.is_a? Instructor
  end
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
	def show
		if is_instructor?(@customer)
			@customers = User.all
		end
	end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  def new
  	@purchase = Purchase.new
  	@packages = Package.all
  	@months = ['01','02','03','04','05','06','07','08','09','10',
  						 '11','12']
  	year = Time.now.year
  	@years = []
  	20.times do
  		@years.push year
  		year += 1
  	end

    @instructors = Instructor.all
  end
    
  #this action executes when the purchase form is submitted
  def create
    puts "create*******"
    puts purchase_params
    user = User.find(session[:user_id])
    email = user.email
  	package_id = params[:purchase][:package]
  	purchase_package = Package.find package_id
  	quantity = purchase_package.quantity.to_s
  	amount = purchase_package.price.to_i
  	StripeModel.chargeCreditCard(params[:stripeToken], email, quantity, amount)
 
  	@purchase = Purchase.new purchase_params
    @purchase.email = email
  	@purchase.quantity = quantity
  	@purchase.price = amount
  	@purchase.save	#save method is overridden in the Purchase model

    redirect_to user_path(session[:user_id])
  end

  private
  def purchase_params
    params.require(:purchase).permit(:package, :name_first, :name_last, :phone, :email, :instructor)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    #render login page
  end

  #when login form is submitted
  def create
  	user = User.authenticate(params[:email], params[:password])
    #check whether user is an instructor or a student
    if is_instructor?(user)
      session[:user_id] = user.id
      redirect_to all_users_path
    elsif user
      session[:user_id] = user.id
      redirect_to user_path(user.id)
      # redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Invalid Login"
      render :new
    end
  end

  #logout
  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :json

  def index
    @orders = current_user.orders
    @orders.sort
  end

  def create
    puts params[:customer]
    @customer = Customer.new user_params
    if @customer
      @customer.code = SecureRandom.urlsafe_base64
      @customer.expires_at = Time.now + 24.hours
      @customer.save
      ActivationMailer.signup_activation(@customer).deliver
      redirect_to login_path, 
      notice: "We've sent a validation email to #{@customer.email}. Please open your email and click the validation link to validate your account"
    else
      render :new
    end
  end

  def new
    @customer = Customer.new
  end

  def show
    @customer = current_user
    if (Order.where(customer_id: @customer.id).count == 0)
      flash[:notice] = "You have no orders"
    end
  end

  #email validation link was clicked, activate new account
  def edit
    @user = User.find_by(code: params[:code])
  	
    if @user
      if @user.expires_at < Time.now
        redirect_to signup_url, alert: "Your code has expired"
      end
    @user.code = nil
    @user.expires_at = nil
    @user.save
    #login the user
    session[:user_id] = @user.id
    redirect_to user_path(@user.id), alert: "Your account has been activated"
    end
  end

  def update
    order_to_update = Order.find params[:orderId]
    lesson_to_update = order_to_update.lessons.find params[:id]
    lesson_to_update.status = params[:status]
    lesson_to_update.dateused = params[:dateused]
    lesson_to_update.save
    render nothing: true
  end

  private

  def user_params
    params.require(:customer).permit(:email, :password, 
                                       :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/credentials_helper.rb
module CredentialsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_contact.html.erb
<ul class="vcard">
  <li class="fn"><%= "#{contact.name_first} #{contact.name_last}" %></li>
  <li><%= contact.email %></li>
  <li><%= contact.phone %></li>
</ul>

app/views/layouts/_header.html.erb
  <header> 
    <div class="row">
      <div class="large-12 columns">
        <nav class="top-bar">
          <ul class="title-area">
            <li class="name"></li>
            <li class="toggle-topbar menu-icon">
              <a href=""><span></span></a>
            </li>
          </ul>
          <section class="top-bar-section">
            <ul class="left">
                <li><a href="#">Dashboard</a></li>
                <li><a href="#">Purchase</a></li>
            </ul>
          </section>
        </nav>
      </div>
    </div>
  </header>

app/views/layouts/_schedule.html.erb
<table class="lessons-table">
  <thead>
    <tr>
      <th class="lesson-column centered">&nbsp;</th>
      <th class="status-column centered">Status</th>
      <% if (current_user.is_a? Instructor) %>
        <th class="date-column centered" id="date-column">Date Used</th>
        <th>&nbsp;</th>
      <% else %>
        <th class="customer-date-column centered" id="customer-date-column">Date Used</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% def add_style(item)
     if (item.status ==  "Used")
        return  "alert"
      else 
        return "success"
      end
    end %>      
    <% schedule.lessons.each_with_index do |lesson, index| %> 
      <tr>
        <td class="centered"><%= index + 1 %></td>
        <td class="centered"><span class="<%=add_style(lesson)%> label" id="label-<%= lesson.id %>" data-id=<%= lesson.id %> data-status=<%= lesson.status %>><%= lesson.status %></span></td>
        <% if (current_user.is_a? Instructor) %>
          <% if lesson.status == 'Available' %>
            <td class="centered" id="tablecell-<%= lesson.id %>"><input type="text" id="date-<%= lesson.id %>" class="datepicker" data-id=<%= lesson.id %>></td>
            <td class="centered">
              <a href="#" class="tiny button toggle" data-id=<%= lesson.id %> data-order-id=<%= schedule.id %>>Submit</a>
            </td>
          <% else %>
            <% unless lesson.dateused.nil? %>
              <td class="centered" id="tablecell-<%= lesson.id %>"><span><%= lesson.dateused.strftime("%d-%m-%y") %></span></td>
            <% end %>
            <td class="button-column centered"><a href="#" class="tiny button toggle" data-id=<%= lesson.id %> data-order-id=<%= schedule.id %>>Edit</a></td>
          <% end %>
        <% else %>
          <% if lesson.status == 'Used' && !lesson.dateused.nil? %>
            <td class="centered"><span><%= lesson.dateused.strftime("%d-%m-%y") %></span></td>  
          <% end %>       
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
    <meta charset="utf-8" />

    <!-- Uncomment to make IE8 render like IE7 -->
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

    <!-- Set the viewport width to device width for mobile -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Match Point</title>
     <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div id="wrapper">
      <header class="clearfix">
        <div id="logo">
          <h1>Match Point</h1>
        </div>
        <!-- <nav id="main-nav" class="clearfix">
          <ul>
            <li><a href="#">DASHBOARD</a></li>
            <li><a href="#">PURCHASE</a></li>          
            <li><a href="#">CONTACT</a></li>
          </ul>
        </nav> -->
        <div id="user_nav">   
          <nav> 
            <ul>  
              <% if name_first %>
                <li>Hi, <%= current_user.name_first %></li>
                <li><%= link_to "Log out", logout_path %></li>
              <% elsif current_user %>
                <li>Logged in as <%= current_user.email %></li>
                <li><%= link_to "Log out", logout_path %></li>
              <% else %>
                <li><%= link_to "Log in", login_path %></li>
                <li><%= link_to "Sign up", signup_path %></li>
              <% end %>
            </ul>
          </nav>
        </div>
      </header>
      <%= yield %>
      <%= javascript_include_tag "application" %>
    </div><!--.#wrapper-->
  </body>
</html>

app/views/purchases/create.html.erb
<h1>Purchases#create</h1>
<p>Find me in app/views/purchases/create.html.erb</p>

app/views/purchases/new.html.erb
<% provide(:title, "Purchase") %>
<div class="wrapper small-12 columns">  
  <div class="row">
    <div class="small-12 small-centered columns">
      <h3 class="dashboard-heading">Purchase Lessons</h3>
    </div>
  </div>
  <%= form_for @purchase, html: {autocomplete: :off} do |form| %>
    <div class="row section">
  		<div class="small-12 columns">
    		<fieldset>     	
          <legend>Package</legend>
    			<% @packages.each do |package| %>
      			<div>
      				<%= form.radio_button(:package, package.id) %>
      				<%= form.label("package_" + package.id.to_s, 
      											package.quantity.to_s + " Lesson $" + 
      											(package.price/100.0).to_s, 
      											data: { quantity: package.quantity.to_s }) %>
      			</div>
      		<% end %>
        </fieldset>
    	</div>	      	
  	</div><!--.row-->
    <div class="row section">
    	 <div class="small-12 columns">
  		  <fieldset>
          <legend>Instructor</legend>
          <select class="selectbox" name="purchase[instructor]">
           <%= @instructors.each do |instructor| %>
             <option value=<%= instructor.id %>><%= instructor.name_last %></option>
           <% end %>
          </select>
        </fieldset>
    	</div>
    </div><!--.row-->
    <div class="row section">
    	<div class="large-12 columns">
    		<%= form.label :first_name %>
    		<%= form.text_field :name_first, value:current_user.name_first, class:"name-field" %>
    	</div>
    </div>
    <div class="row section">
    	<div class="small-12 columns">
    		<%= form.label :last_name %>
    		<%= form.text_field :name_last, value:current_user.name_last, class:"name-field" %>
    	</div>
    </div>
   	<div class="row section">
    	<div class="small-12 columns">
    		<%= form.label :phone %>
    		<%= form.text_field :phone, value:current_user.phone, class:"phone" %>
    	</div>
    </div>
    <div class="row section">
    	<div class="small-12 columns">
    		<div class="payment-errors"></div>
    		<label>
    			<span>Card Number</span>
    			<input type="text" size="20" class="number" data-stripe="number"/>
    		</label>
    	</div>
    </div>
  	<div class="row section">
  	  <div class="small-12 columns">
  	    <label>
  	      <span>CVC</span>
  	      <input type="text" size="4" class="cvc" data-stripe="cvc"/>
  	  	</label>
  	  </div>
  	</div>
    <div class="row section">
      <div class="small-12 columns">
        <label>
          <span>Expiration Date</span>
      </div>
    </div>
    <div class="row section">
    	<div class="small-12 columns">
          <select class="creditcardselect" data-stripe="exp-month">
            <%= @months.each do |month| %>
              <option value=<%= month %>><%= month %></option>
            <% end %>
          </select>
          <!--<input type="select" size="2" data-stripe="exp-month"/>-->
        </label>
        
        <select class="creditcardselect" data-stripe="exp-year">
          <%= @years.each do |year| %>
            <option value=<%= year %>><%= year %></option>
          <% end %>
        </select>
        <!--<input type="select" size="4" data-stripe="exp-year"/>-->
      </div>
    </div>
   <!-- </div> -->
    <!--show the order summary-->
    <div id="summary_name_first"></div>
    <div id="summary_name_last"></div>
    <div id="summary_phone"></div>
    <div id="summary_payment_method"></div>
    <div>
      <% @packages.each do |package| %>
  	    <div id = "<%= package.id.to_s %>selected" class="hidden-package"> <%= package.quantity %> Lessons for $<%= (package.price/100.0).to_s %> 
  	    </div>
  	  <% end %>
  	</div>
  	<div class="row">
  		<div class="small-12 columns">
  			<%= form.submit "Purchase", class: "button" %>
  		</div>
  	</div>	  
  <% end %>
</div>
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<script>
  // This identifies your website in the createToken call
  Stripe.setPublishableKey('pk_test_GE3dSmLHzDugfJTxr29lkUeg');
</script>

app/views/users/edit.html.erb
<h3>Your email address has been validated!</h3>
<h1>Personal Info</h1>
<%= form_for @user, url: users_path, html:{ autocomplete: :off } do |form| %>
	<div class="content" data-section-content>
    <div class="row">
    	<div class="small-8 columns">
				<%= form.label :first_name, class: "small-6 columns" %>
				<%= form.text_field :name_first, class: "small-6 columns" %>
			</div>
		</div>
		<div class="row">
    	<div class="small-8 columns">
				<%= form.label :last_name, class: "small-6 columns" %>
				<%= form.text_field :name_last, class: "small-6 columns" %>
			</div>
		</div>
		<div class="row">
    	<div class="small-8 columns">
				<%= form.label :phone, class: "small-6 columns" %>
				<%= form.text_field :phone, class: "small-6 columns" %>
			</div>
		</div>
		<!--send the code as a hidden field so we know who's account to update-->
		<%= form.hidden_field :code %>
		<div><%= form.submit "Submit", :class => "small button" %></div>
	</div><!--.content-->
<% end %>

app/views/users/index.html.erb
<div class="wrapper small-12 columns row">	
	<div class="row">
	  <div class="small-12 small-centered columns">
	  	<h3 class="dashboard-heading">Instructor Dashboard</h3>
	  </div>
	</div>

	<% @orders.each_with_index do |order, index| %>
		<div class="panel">
			<div class="row">
			  <div class="large-12 columns">
					<%= render partial: "layouts/contact", object: order.customer %>		
				</div>
			</div>
			<div class="row">
			  <div class="large-12 columns">
					<%= render partial: "layouts/schedule", object: order %>		  	
				</div>
			</div>
		</div>
	<% end %>
</div>

<%#= render partial: "layouts/schedule", collection: @customers %>

app/views/users/new.html.erb
<div id="login-container" class="login-wrapper">   
  <div class="row">
    <div class="small-12 columns"><h3>Signup</h3></div>
  </div>

  <%= form_for @customer, url: users_path, html: {autocomplete: :off} do |form| %>
    <% if @customer.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <% for message in @customer.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div><!--.error_messages-->
    <% end %>
  <div class="row">
    <div class="small-8 columns">
      <%= form.label :email, class: "small-3 columns"%>
      <%= form.text_field(:email, class: "small-9 columns") %>
    </div>
  </div>
    <div class="row">
      <div class="small-8 columns">
        <%= form.label :password, class: "small-3 columns"%>
        <%= form.text_field(:password, class: "small-9 columns") %>
      </div>
    </div>
    <div class="row">
      <div class="small-8 columns">
        <%= form.label :password_confirmation, class: "small-3 columns"%>
        <%= form.text_field(:password_confirmation, class: "small-9 columns") %>
      </div>
    </div>
    <div class="row">  
      <div class="small-12 columns">     
        <div><%= form.submit "Register", :class => "button" %></div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="wrapper small-12 columns row">	
	<div class="row">
	  <div class="small-12 small-centered columns">
	  	<h3 class="dashboard-heading"><%= "#{@customer.name_first}'s Dashboard" unless @customer.name_first.nil? %></h3>
	  	<a href=<%= purchase_path %> id="purchase-button-top" class="small button">Purchase Lessons</a>
	  </div>
	</div>

	<% @customer.orders.each_with_index do |order, index| %>
		<div class="panel">
			<div class="row">
			  <div class="large-12 columns">
			  	<%= render partial: "layouts/contact", object: order.instructor %>
				</div>
				<div class="large-12 columns">
					<%= render partial: "layouts/schedule", object: order %>
			  </div>
			</div><!--end .row-->
		</div>
	<% end %>
		
	<div class="row">
		<div class="large-12 columns">
			<a href=<%= purchase_path %> id="purchase-button" class="small button">Purchase Lessons</a>
		</div>
	</div>
</div>